//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Route = new HashSet<Route>();
            this.Route1 = new HashSet<Route>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public Nullable<int> employeeTypeId { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<Route> Route { get; set; }
        public virtual ICollection<Route> Route1 { get; set; }
    }
}
