//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStudent
    {
        public int id { get; set; }
        public Nullable<int> routeId { get; set; }
        public Nullable<int> studentId { get; set; }
        public Nullable<int> orderInRoute { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Student Student { get; set; }
    }
}
