//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.RouteStudent = new HashSet<RouteStudent>();
        }
    
        public int id { get; set; }
        public Nullable<int> busId { get; set; }
        public Nullable<int> routeScheduleId { get; set; }
        public Nullable<bool> goingToSchool { get; set; }
        public Nullable<bool> goingToHome { get; set; }
        public Nullable<int> pilotId { get; set; }
        public Nullable<int> copilotId { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual RouteSchedule RouteSchedule { get; set; }
        public virtual ICollection<RouteStudent> RouteStudent { get; set; }
    }
}
