//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buseta_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.RouteStudent = new HashSet<RouteStudent>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public Nullable<int> personInChargeId { get; set; }
        public Nullable<int> schoolId { get; set; }
    
        public virtual PersonInCharge PersonInCharge { get; set; }
        public virtual ICollection<RouteStudent> RouteStudent { get; set; }
        public virtual School School { get; set; }
    }
}
