//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Route_BusId", "Bus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.Bus), "Route", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Route), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Employee_EmployeeTypeId", "EmployeeType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.EmployeeType), "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Employee), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Route_CopilotId", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.Employee), "Route", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Route), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Route_PilotId", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.Employee), "Route", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Route), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Student_PersonInChargeId", "PersonInCharge", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.PersonInCharge), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Student), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Route_RouteScheduleId", "RouteSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.RouteSchedule), "Route", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Route), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_RouteStudent_RouteId", "Route", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.Route), "RouteStudent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.RouteStudent), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_RouteStudent_StudentId", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.Student), "RouteStudent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.RouteStudent), true)]
[assembly: EdmRelationshipAttribute("BusetasModel", "fk_Student_SchoolId", "School", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Busetas_DataAccess.School), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Busetas_DataAccess.Student), true)]

#endregion

namespace Busetas_DataAccess
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BusetasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BusetasEntities usando la cadena de conexión encontrada en la sección 'BusetasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BusetasEntities() : base("name=BusetasEntities", "BusetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BusetasEntities.
        /// </summary>
        public BusetasEntities(string connectionString) : base(connectionString, "BusetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BusetasEntities.
        /// </summary>
        public BusetasEntities(EntityConnection connection) : base(connection, "BusetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Bus> Bus
        {
            get
            {
                if ((_Bus == null))
                {
                    _Bus = base.CreateObjectSet<Bus>("Bus");
                }
                return _Bus;
            }
        }
        private ObjectSet<Bus> _Bus;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EmployeeType> EmployeeType
        {
            get
            {
                if ((_EmployeeType == null))
                {
                    _EmployeeType = base.CreateObjectSet<EmployeeType>("EmployeeType");
                }
                return _EmployeeType;
            }
        }
        private ObjectSet<EmployeeType> _EmployeeType;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PersonInCharge> PersonInCharge
        {
            get
            {
                if ((_PersonInCharge == null))
                {
                    _PersonInCharge = base.CreateObjectSet<PersonInCharge>("PersonInCharge");
                }
                return _PersonInCharge;
            }
        }
        private ObjectSet<PersonInCharge> _PersonInCharge;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Route> Route
        {
            get
            {
                if ((_Route == null))
                {
                    _Route = base.CreateObjectSet<Route>("Route");
                }
                return _Route;
            }
        }
        private ObjectSet<Route> _Route;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RouteSchedule> RouteSchedule
        {
            get
            {
                if ((_RouteSchedule == null))
                {
                    _RouteSchedule = base.CreateObjectSet<RouteSchedule>("RouteSchedule");
                }
                return _RouteSchedule;
            }
        }
        private ObjectSet<RouteSchedule> _RouteSchedule;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RouteStudent> RouteStudent
        {
            get
            {
                if ((_RouteStudent == null))
                {
                    _RouteStudent = base.CreateObjectSet<RouteStudent>("RouteStudent");
                }
                return _RouteStudent;
            }
        }
        private ObjectSet<RouteStudent> _RouteStudent;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<School> School
        {
            get
            {
                if ((_School == null))
                {
                    _School = base.CreateObjectSet<School>("School");
                }
                return _School;
            }
        }
        private ObjectSet<School> _School;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Student> Student
        {
            get
            {
                if ((_Student == null))
                {
                    _Student = base.CreateObjectSet<Student>("Student");
                }
                return _Student;
            }
        }
        private ObjectSet<Student> _Student;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Bus. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBus(Bus bus)
        {
            base.AddObject("Bus", bus);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Employee. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EmployeeType. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmployeeType(EmployeeType employeeType)
        {
            base.AddObject("EmployeeType", employeeType);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PersonInCharge. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPersonInCharge(PersonInCharge personInCharge)
        {
            base.AddObject("PersonInCharge", personInCharge);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Route. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRoute(Route route)
        {
            base.AddObject("Route", route);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet RouteSchedule. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRouteSchedule(RouteSchedule routeSchedule)
        {
            base.AddObject("RouteSchedule", routeSchedule);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet RouteStudent. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRouteStudent(RouteStudent routeStudent)
        {
            base.AddObject("RouteStudent", routeStudent);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet School. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSchool(School school)
        {
            base.AddObject("School", school);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Student. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToStudent(Student student)
        {
            base.AddObject("Student", student);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="Bus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bus : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Bus.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Bus CreateBus(global::System.Int32 id)
        {
            Bus bus = new Bus();
            bus.id = id;
            return bus;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String brand
        {
            get
            {
                return _brand;
            }
            set
            {
                OnbrandChanging(value);
                ReportPropertyChanging("brand");
                _brand = StructuralObject.SetValidValue(value, true, "brand");
                ReportPropertyChanged("brand");
                OnbrandChanged();
            }
        }
        private global::System.String _brand;
        partial void OnbrandChanging(global::System.String value);
        partial void OnbrandChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String color
        {
            get
            {
                return _color;
            }
            set
            {
                OncolorChanging(value);
                ReportPropertyChanging("color");
                _color = StructuralObject.SetValidValue(value, true, "color");
                ReportPropertyChanged("color");
                OncolorChanged();
            }
        }
        private global::System.String _color;
        partial void OncolorChanging(global::System.String value);
        partial void OncolorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> capacity
        {
            get
            {
                return _capacity;
            }
            set
            {
                OncapacityChanging(value);
                ReportPropertyChanging("capacity");
                _capacity = StructuralObject.SetValidValue(value, "capacity");
                ReportPropertyChanged("capacity");
                OncapacityChanged();
            }
        }
        private Nullable<global::System.Int32> _capacity;
        partial void OncapacityChanging(Nullable<global::System.Int32> value);
        partial void OncapacityChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_BusId", "Route")]
        public EntityCollection<Route> Route
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Route>("BusetasModel.fk_Route_BusId", "Route");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Route>("BusetasModel.fk_Route_BusId", "Route", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Employee.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Employee CreateEmployee(global::System.Int32 id)
        {
            Employee employee = new Employee();
            employee.id = id;
            return employee;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, true, "lastname");
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, true, "telephone");
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> employeeTypeId
        {
            get
            {
                return _employeeTypeId;
            }
            set
            {
                OnemployeeTypeIdChanging(value);
                ReportPropertyChanging("employeeTypeId");
                _employeeTypeId = StructuralObject.SetValidValue(value, "employeeTypeId");
                ReportPropertyChanged("employeeTypeId");
                OnemployeeTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _employeeTypeId;
        partial void OnemployeeTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnemployeeTypeIdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Employee_EmployeeTypeId", "EmployeeType")]
        public EmployeeType EmployeeType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmployeeType>("BusetasModel.fk_Employee_EmployeeTypeId", "EmployeeType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmployeeType>("BusetasModel.fk_Employee_EmployeeTypeId", "EmployeeType").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EmployeeType> EmployeeTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmployeeType>("BusetasModel.fk_Employee_EmployeeTypeId", "EmployeeType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EmployeeType>("BusetasModel.fk_Employee_EmployeeTypeId", "EmployeeType", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_CopilotId", "Route")]
        public EntityCollection<Route> Route
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Route>("BusetasModel.fk_Route_CopilotId", "Route");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Route>("BusetasModel.fk_Route_CopilotId", "Route", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_PilotId", "Route")]
        public EntityCollection<Route> Route1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Route>("BusetasModel.fk_Route_PilotId", "Route");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Route>("BusetasModel.fk_Route_PilotId", "Route", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="EmployeeType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmployeeType : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EmployeeType.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static EmployeeType CreateEmployeeType(global::System.Int32 id)
        {
            EmployeeType employeeType = new EmployeeType();
            employeeType.id = id;
            return employeeType;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> salary
        {
            get
            {
                return _salary;
            }
            set
            {
                OnsalaryChanging(value);
                ReportPropertyChanging("salary");
                _salary = StructuralObject.SetValidValue(value, "salary");
                ReportPropertyChanged("salary");
                OnsalaryChanged();
            }
        }
        private Nullable<global::System.Decimal> _salary;
        partial void OnsalaryChanging(Nullable<global::System.Decimal> value);
        partial void OnsalaryChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Employee_EmployeeTypeId", "Employee")]
        public EntityCollection<Employee> Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("BusetasModel.fk_Employee_EmployeeTypeId", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("BusetasModel.fk_Employee_EmployeeTypeId", "Employee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="PersonInCharge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PersonInCharge : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PersonInCharge.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static PersonInCharge CreatePersonInCharge(global::System.Int32 id)
        {
            PersonInCharge personInCharge = new PersonInCharge();
            personInCharge.id = id;
            return personInCharge;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true, "lastName");
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, true, "telephone");
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Student_PersonInChargeId", "Student")]
        public EntityCollection<Student> Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("BusetasModel.fk_Student_PersonInChargeId", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("BusetasModel.fk_Student_PersonInChargeId", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="Route")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Route : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Route.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Route CreateRoute(global::System.Int32 id)
        {
            Route route = new Route();
            route.id = id;
            return route;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> busId
        {
            get
            {
                return _busId;
            }
            set
            {
                OnbusIdChanging(value);
                ReportPropertyChanging("busId");
                _busId = StructuralObject.SetValidValue(value, "busId");
                ReportPropertyChanged("busId");
                OnbusIdChanged();
            }
        }
        private Nullable<global::System.Int32> _busId;
        partial void OnbusIdChanging(Nullable<global::System.Int32> value);
        partial void OnbusIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> routeScheduleId
        {
            get
            {
                return _routeScheduleId;
            }
            set
            {
                OnrouteScheduleIdChanging(value);
                ReportPropertyChanging("routeScheduleId");
                _routeScheduleId = StructuralObject.SetValidValue(value, "routeScheduleId");
                ReportPropertyChanged("routeScheduleId");
                OnrouteScheduleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _routeScheduleId;
        partial void OnrouteScheduleIdChanging(Nullable<global::System.Int32> value);
        partial void OnrouteScheduleIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> goingToSchool
        {
            get
            {
                return _goingToSchool;
            }
            set
            {
                OngoingToSchoolChanging(value);
                ReportPropertyChanging("goingToSchool");
                _goingToSchool = StructuralObject.SetValidValue(value, "goingToSchool");
                ReportPropertyChanged("goingToSchool");
                OngoingToSchoolChanged();
            }
        }
        private Nullable<global::System.Boolean> _goingToSchool;
        partial void OngoingToSchoolChanging(Nullable<global::System.Boolean> value);
        partial void OngoingToSchoolChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> goingToHome
        {
            get
            {
                return _goingToHome;
            }
            set
            {
                OngoingToHomeChanging(value);
                ReportPropertyChanging("goingToHome");
                _goingToHome = StructuralObject.SetValidValue(value, "goingToHome");
                ReportPropertyChanged("goingToHome");
                OngoingToHomeChanged();
            }
        }
        private Nullable<global::System.Boolean> _goingToHome;
        partial void OngoingToHomeChanging(Nullable<global::System.Boolean> value);
        partial void OngoingToHomeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pilotId
        {
            get
            {
                return _pilotId;
            }
            set
            {
                OnpilotIdChanging(value);
                ReportPropertyChanging("pilotId");
                _pilotId = StructuralObject.SetValidValue(value, "pilotId");
                ReportPropertyChanged("pilotId");
                OnpilotIdChanged();
            }
        }
        private Nullable<global::System.Int32> _pilotId;
        partial void OnpilotIdChanging(Nullable<global::System.Int32> value);
        partial void OnpilotIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> copilotId
        {
            get
            {
                return _copilotId;
            }
            set
            {
                OncopilotIdChanging(value);
                ReportPropertyChanging("copilotId");
                _copilotId = StructuralObject.SetValidValue(value, "copilotId");
                ReportPropertyChanged("copilotId");
                OncopilotIdChanged();
            }
        }
        private Nullable<global::System.Int32> _copilotId;
        partial void OncopilotIdChanging(Nullable<global::System.Int32> value);
        partial void OncopilotIdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_BusId", "Bus")]
        public Bus Bus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bus>("BusetasModel.fk_Route_BusId", "Bus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bus>("BusetasModel.fk_Route_BusId", "Bus").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bus> BusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bus>("BusetasModel.fk_Route_BusId", "Bus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bus>("BusetasModel.fk_Route_BusId", "Bus", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_CopilotId", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("BusetasModel.fk_Route_CopilotId", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("BusetasModel.fk_Route_CopilotId", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("BusetasModel.fk_Route_CopilotId", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("BusetasModel.fk_Route_CopilotId", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_PilotId", "Employee")]
        public Employee Employee1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("BusetasModel.fk_Route_PilotId", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("BusetasModel.fk_Route_PilotId", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> Employee1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("BusetasModel.fk_Route_PilotId", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("BusetasModel.fk_Route_PilotId", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_RouteScheduleId", "RouteSchedule")]
        public RouteSchedule RouteSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteSchedule>("BusetasModel.fk_Route_RouteScheduleId", "RouteSchedule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteSchedule>("BusetasModel.fk_Route_RouteScheduleId", "RouteSchedule").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RouteSchedule> RouteScheduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteSchedule>("BusetasModel.fk_Route_RouteScheduleId", "RouteSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RouteSchedule>("BusetasModel.fk_Route_RouteScheduleId", "RouteSchedule", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_RouteStudent_RouteId", "RouteStudent")]
        public EntityCollection<RouteStudent> RouteStudent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RouteStudent>("BusetasModel.fk_RouteStudent_RouteId", "RouteStudent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RouteStudent>("BusetasModel.fk_RouteStudent_RouteId", "RouteStudent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="RouteSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RouteSchedule : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RouteSchedule.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static RouteSchedule CreateRouteSchedule(global::System.Int32 id)
        {
            RouteSchedule routeSchedule = new RouteSchedule();
            routeSchedule.id = id;
            return routeSchedule;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dayOfTheWeek
        {
            get
            {
                return _dayOfTheWeek;
            }
            set
            {
                OndayOfTheWeekChanging(value);
                ReportPropertyChanging("dayOfTheWeek");
                _dayOfTheWeek = StructuralObject.SetValidValue(value, true, "dayOfTheWeek");
                ReportPropertyChanged("dayOfTheWeek");
                OndayOfTheWeekChanged();
            }
        }
        private global::System.String _dayOfTheWeek;
        partial void OndayOfTheWeekChanging(global::System.String value);
        partial void OndayOfTheWeekChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, "StartTime");
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value, "EndTime");
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnEndTimeChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Route_RouteScheduleId", "Route")]
        public EntityCollection<Route> Route
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Route>("BusetasModel.fk_Route_RouteScheduleId", "Route");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Route>("BusetasModel.fk_Route_RouteScheduleId", "Route", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="RouteStudent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RouteStudent : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RouteStudent.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static RouteStudent CreateRouteStudent(global::System.Int32 id)
        {
            RouteStudent routeStudent = new RouteStudent();
            routeStudent.id = id;
            return routeStudent;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> routeId
        {
            get
            {
                return _routeId;
            }
            set
            {
                OnrouteIdChanging(value);
                ReportPropertyChanging("routeId");
                _routeId = StructuralObject.SetValidValue(value, "routeId");
                ReportPropertyChanged("routeId");
                OnrouteIdChanged();
            }
        }
        private Nullable<global::System.Int32> _routeId;
        partial void OnrouteIdChanging(Nullable<global::System.Int32> value);
        partial void OnrouteIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                OnstudentIdChanging(value);
                ReportPropertyChanging("studentId");
                _studentId = StructuralObject.SetValidValue(value, "studentId");
                ReportPropertyChanged("studentId");
                OnstudentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _studentId;
        partial void OnstudentIdChanging(Nullable<global::System.Int32> value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> orderInRoute
        {
            get
            {
                return _orderInRoute;
            }
            set
            {
                OnorderInRouteChanging(value);
                ReportPropertyChanging("orderInRoute");
                _orderInRoute = StructuralObject.SetValidValue(value, "orderInRoute");
                ReportPropertyChanged("orderInRoute");
                OnorderInRouteChanged();
            }
        }
        private Nullable<global::System.Int32> _orderInRoute;
        partial void OnorderInRouteChanging(Nullable<global::System.Int32> value);
        partial void OnorderInRouteChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_RouteStudent_RouteId", "Route")]
        public Route Route
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Route>("BusetasModel.fk_RouteStudent_RouteId", "Route").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Route>("BusetasModel.fk_RouteStudent_RouteId", "Route").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Route> RouteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Route>("BusetasModel.fk_RouteStudent_RouteId", "Route");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Route>("BusetasModel.fk_RouteStudent_RouteId", "Route", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_RouteStudent_StudentId", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BusetasModel.fk_RouteStudent_StudentId", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BusetasModel.fk_RouteStudent_StudentId", "Student").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BusetasModel.fk_RouteStudent_StudentId", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("BusetasModel.fk_RouteStudent_StudentId", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="School")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class School : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto School.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static School CreateSchool(global::System.Int32 id)
        {
            School school = new School();
            school.id = id;
            return school;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Student_SchoolId", "Student")]
        public EntityCollection<Student> Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("BusetasModel.fk_Student_SchoolId", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("BusetasModel.fk_Student_SchoolId", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusetasModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Student.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Student CreateStudent(global::System.Int32 id)
        {
            Student student = new Student();
            student.id = id;
            return student;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true, "lastName");
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, "age");
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, true, "telephone");
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> personInChargeId
        {
            get
            {
                return _personInChargeId;
            }
            set
            {
                OnpersonInChargeIdChanging(value);
                ReportPropertyChanging("personInChargeId");
                _personInChargeId = StructuralObject.SetValidValue(value, "personInChargeId");
                ReportPropertyChanged("personInChargeId");
                OnpersonInChargeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _personInChargeId;
        partial void OnpersonInChargeIdChanging(Nullable<global::System.Int32> value);
        partial void OnpersonInChargeIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> schoolId
        {
            get
            {
                return _schoolId;
            }
            set
            {
                OnschoolIdChanging(value);
                ReportPropertyChanging("schoolId");
                _schoolId = StructuralObject.SetValidValue(value, "schoolId");
                ReportPropertyChanged("schoolId");
                OnschoolIdChanged();
            }
        }
        private Nullable<global::System.Int32> _schoolId;
        partial void OnschoolIdChanging(Nullable<global::System.Int32> value);
        partial void OnschoolIdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Student_PersonInChargeId", "PersonInCharge")]
        public PersonInCharge PersonInCharge
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonInCharge>("BusetasModel.fk_Student_PersonInChargeId", "PersonInCharge").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonInCharge>("BusetasModel.fk_Student_PersonInChargeId", "PersonInCharge").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PersonInCharge> PersonInChargeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonInCharge>("BusetasModel.fk_Student_PersonInChargeId", "PersonInCharge");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PersonInCharge>("BusetasModel.fk_Student_PersonInChargeId", "PersonInCharge", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_RouteStudent_StudentId", "RouteStudent")]
        public EntityCollection<RouteStudent> RouteStudent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RouteStudent>("BusetasModel.fk_RouteStudent_StudentId", "RouteStudent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RouteStudent>("BusetasModel.fk_RouteStudent_StudentId", "RouteStudent", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusetasModel", "fk_Student_SchoolId", "School")]
        public School School
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<School>("BusetasModel.fk_Student_SchoolId", "School").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<School>("BusetasModel.fk_Student_SchoolId", "School").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<School> SchoolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<School>("BusetasModel.fk_Student_SchoolId", "School");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<School>("BusetasModel.fk_Student_SchoolId", "School", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
